export interface Post {
    user: string
    description: string
    content: string
    eHex: string
    nHex: string
}

export const dummyImages =  [
    {
        user: "JP",
        description: "MG & Comment -_-",
        content: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAZABQDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcBAgUI/8QAKRAAAgEDAwIFBQEAAAAAAAAAAQIDBAURAAYhBxITFCIjMQhBUWFxFf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAABEh/9oADAMBAAIRAxEAPwB3bx6qbZ2luKmsl2mqfPzxiQLDAXCg57QT+WKkDGf3jUbR6pWLc94htlLFcaWqnR3hFXT9iy9oDMAQTyAwPONLL6kztmn3JZJq2h8a5BleqxD6pKc5RQrkjlSxOF5z+ONL3cM9rt96pKWjWsilalYRe7KUEoIZ890jAe2Rx+x/RLshMrsvRrK2pVCs21aqnveTxaWJizghmJQZJzzn+6NUL7qh0VtW/wC+/wCrW3Gppqjy6wgJGrgFGJVhn4HqYEffj4xrP2v0EtNruAlu1ct5o1UotNPRpGEHcGXtZCCCDnPzkEg8E6c2jQVjRIo1SNQqKAFUDAAH2GjVtGg//9k=",
        eHex: "",
        nHex: ""
    },
    {
        user: "Star",
        description: "Look my new post",
        content: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAZABQDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcBAgUI/8QAKRAAAgEDAwIFBQEAAAAAAAAAAQIDBAURAAYhBxITFCIjMQhBUWFxFf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAABEh/9oADAMBAAIRAxEAPwB3bx6qbZ2luKmsl2mqfPzxiQLDAXCg57QT+WKkDGf3jUbR6pWLc94htlLFcaWqnR3hFXT9iy9oDMAQTyAwPONLL6kztmn3JZJq2h8a5BleqxD6pKc5RQrkjlSxOF5z+ONL3cM9rt96pKWjWsilalYRe7KUEoIZ890jAe2Rx+x/RLshMrsvRrK2pVCs21aqnveTxaWJizghmJQZJzzn+6NUL7qh0VtW/wC+/wCrW3Gppqjy6wgJGrgFGJVhn4HqYEffj4xrP2v0EtNruAlu1ct5o1UotNPRpGEHcGXtZCCCDnPzkEg8E6c2jQVjRIo1SNQqKAFUDAAH2GjVtGg//9k=",
        eHex: "",
        nHex: ""
    },
    {
        user: "Santa",
        description: "HOHOHO",
        content: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAZABQDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAcBAgUI/8QAKRAAAgEDAwIFBQEAAAAAAAAAAQIDBAURAAYhBxITFCIjMQhBUWFxFf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAABEh/9oADAMBAAIRAxEAPwB3bx6qbZ2luKmsl2mqfPzxiQLDAXCg57QT+WKkDGf3jUbR6pWLc94htlLFcaWqnR3hFXT9iy9oDMAQTyAwPONLL6kztmn3JZJq2h8a5BleqxD6pKc5RQrkjlSxOF5z+ONL3cM9rt96pKWjWsilalYRe7KUEoIZ890jAe2Rx+x/RLshMrsvRrK2pVCs21aqnveTxaWJizghmJQZJzzn+6NUL7qh0VtW/wC+/wCrW3Gppqjy6wgJGrgFGJVhn4HqYEffj4xrP2v0EtNruAlu1ct5o1UotNPRpGEHcGXtZCCCDnPzkEg8E6c2jQVjRIo1SNQqKAFUDAAH2GjVtGg//9k=",
        eHex: "",
        nHex: ""
    } 
]
